const variables = {
    dplX: 0,
    dplXOiseau: 0,
    dplXOiseau2: 0,
    dplXGlobal: 0,
    dplXGlobalOiseau: 0,
    dplXGlobalOiseau2: 0,
    vitesse: 30,
    compteurDeClic: 0,
    vitesseOiseau: 10,
    vitesseOiseau2: 15,
    direction: 0,
    hauteur: 0,
    direction2: 0,
    hauteur2: 0,
    largeurEcran: window.innerWidth,
    hauteurEcran: window.innerHeight,
    constanteAjustementhauteurEcran: window.innerHeight / window.innerWidth,
    constanteAjustementLargeurEcran: 0.87,
    constanteAjustementLargeurEcranOiseau: 0.92,
    dplXChaudron: 0,
    dplXGlobalChaudron: 0,
    vitesseChaudron: 0,
    level1:50,
    level2:150,
    level2Fin:200,

    backgroundFinishItem: 0,
    objetCollision: [
      "#magicPotions",
      "#bouclier",
      "#papyrus2",
      "#fireBall",
      "#sword",
      "#CoinsA",
      "#CoinsB",
      "#CoinsB1",
      "#CoinsB",
      "#CoinsB1",
      "#CoinsC",
      "#CoinsD",
      "#endGame"
    ]
  };

  export default variables;